<a href="https://colab.research.google.com/github/SonyZaman/Python/blob/main/17_Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [17]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
np.arange(1,11,2,dtype=float)

array([1., 3., 5., 7., 9.])

In [27]:
# with reshape
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
np.arange(16,dtype=float).reshape(2,2,2,2)

array([[[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]]],


       [[[ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.]]]])

In [15]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
np.ones(())

array(1.)

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
# np.random
np.random.random((3,4))

array([[0.48138885, 0.43856484, 0.77136021, 0.78844632],
       [0.20250787, 0.90530292, 0.95092224, 0.07155688],
       [0.9365298 , 0.63572553, 0.80325604, 0.5242706 ]])

In [44]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [45]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Array Attributes

In [55]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [57]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [58]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [59]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
# ndim(return dimension)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [60]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [61]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [66]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [67]:
# itemsize (return per item memory size in byte)
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


### Changing Datatype

In [84]:
# astype
print(a3,end="\n\n")
print(a3.dtype,end="\n\n")
print(a3.itemsize,end="\n\n")

a3 = a3.astype(np.int64)
print(a3,end="\n\n")
print(a3.dtype,end="\n\n")
print(a3.itemsize,end="\n\n")

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

int64

8

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

int64

8



### Array Operations

In [86]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1,end='\n\n')
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [91]:
# scalar operations

# arithmetic
print(a1 + 1, end='\n\n')
print(a1 - 1, end='\n\n')
print(a1 * 2, end='\n\n')
print(a1 / 2, end='\n\n')
print(a1 ** 2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [90]:
# relational
print(a1 > 5, end='\n\n')
print(a2 == 15)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

[[False False False  True]
 [False False False False]
 [False False False False]]


In [92]:
# vector operations
# arithmetic
print(a1 + a2, end='\n\n')
print(a1 - a2, end='\n\n')
print(a1 * a2, end='\n\n')
print(a1 ** a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


### Array Functions

In [111]:
a1 = np.arange(9).reshape(3,3)
a1 = np.round(a1*5)
a1

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [112]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

40
0
180
0


In [115]:
a1

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [117]:
# 0 -> col(return max/min/sum/product of each column)
print(np.max(a1,axis=0))
print(np.min(a1,axis=0))
print(np.sum(a1,axis=0))
print(np.prod(a1,axis=0))

[30 35 40]
[ 0  5 10]
[45 60 75]
[    0  3500 10000]


In [118]:
# 1 -> row(return max/min/sum/product of each row)
print(np.max(a1,axis=1))
print(np.min(a1,axis=1))
print(np.sum(a1,axis=1))
print(np.prod(a1,axis=1))

[10 25 40]
[ 0 15 30]
[ 15  60 105]
[    0  7500 42000]


In [122]:
a1

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [119]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

20.0
20.0
12.909944487358056
166.66666666666666


In [120]:
# column wise
print(np.mean(a1,axis=0))
print(np.median(a1,axis=0))
print(np.std(a1,axis=0))
print(np.var(a1,axis=0))

[15. 20. 25.]
[15. 20. 25.]
[12.24744871 12.24744871 12.24744871]
[150. 150. 150.]


In [121]:
# row wise
print(np.mean(a1,axis=1))
print(np.median(a1,axis=1))
print(np.std(a1,axis=1))
print(np.var(a1,axis=1))

[ 5. 20. 35.]
[ 5. 20. 35.]
[4.0824829 4.0824829 4.0824829]
[16.66666667 16.66666667 16.66666667]


In [125]:
# trigonomoetric functions
print(np.sin(a1),end='\n\n')
print(np.tan(a1),end='\n\n')
print(np.cos(a1))

[[ 0.         -0.95892427 -0.54402111]
 [ 0.65028784  0.91294525 -0.13235175]
 [-0.98803162 -0.42818267  0.74511316]]

[[ 0.         -3.38051501  0.64836083]
 [-0.8559934   2.23716094 -0.13352641]
 [-6.4053312   0.47381472 -1.11721493]]

[[ 1.          0.28366219 -0.83907153]
 [-0.75968791  0.40808206  0.99120281]
 [ 0.15425145 -0.90369221 -0.66693806]]


In [126]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [128]:
# log and exponents
print(np.log(a1),end='\n\n')
print(np.exp(a1))

[[      -inf 1.60943791 2.30258509]
 [2.7080502  2.99573227 3.21887582]
 [3.40119738 3.55534806 3.68887945]]

[[1.00000000e+00 1.48413159e+02 2.20264658e+04]
 [3.26901737e+06 4.85165195e+08 7.20048993e+10]
 [1.06864746e+13 1.58601345e+15 2.35385267e+17]]


/tmp/ipykernel_4247/4067934327.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1),end='\n\n')


In [129]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[28., 94., 94.],
       [52., 20.,  1.]])

In [131]:
np.floor(np.random.random((2,3))*100)

array([[43., 89., 35.],
       [90.,  3.,  5.]])

In [130]:
np.ceil(np.random.random((2,3))*100)

array([[89., 34., 64.],
       [52., 34., 67.]])

### Indexing and Slicing

In [132]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

Indexing

In [147]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
a1[-2]

np.int64(8)

In [134]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
a2[1,0]

np.int64(4)

In [150]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [149]:
a3[1,0,1]

np.int64(5)

Slicing

In [152]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a1[2:5]

array([2, 3, 4])

In [154]:
a1[2:7:2]

array([2, 4, 6])

In [155]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
# 0 1 2 3
a2[0,:]

array([0, 1, 2, 3])

In [159]:
''' 2
    6
    10'''
a2[:,2]

array([ 2,  6, 10])

In [163]:
''' 5 6
    9 10'''
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [164]:
# 0   3

# 8   11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [165]:
''' 1   3
    9   11'''
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [168]:
''' 1 2 3
    5 6 7'''
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [166]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [169]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [170]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [173]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [176]:
a3[0,1,:]

array([3, 4, 5])

In [177]:
a3[1,:,1]

array([10, 13, 16])

In [174]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [179]:
'''22 23
   25 26'''

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [181]:
'''0  2

  18 20'''
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [182]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [184]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [185]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [186]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [188]:
# nditer -> It converts a multi-dimensional array into a 1D sequence (for iteration only)
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [198]:
# reshape
a = np.array([1,2,3,4,5,6])

# reshape → change shape (same data, different structure)
b = a.reshape(2,3)

print(b)

[[1 2 3]
 [4 5 6]]


In [200]:
# Transpose
a = np.array([[1,2,3],
              [4,5,6]])

# transpose → swap rows and columns
b = a.T

print(b)

[[1 4]
 [2 5]
 [3 6]]


In [201]:
# ravel
a = np.array([[1,2],
              [3,4]])

# ravel → convert multi-dimensional array into 1D
b = a.ravel()

print(b)

[1 2 3 4]


### Stacking

In [202]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4,end='\n\n')
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [204]:
# Horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [206]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [208]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
# Horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [214]:
# Vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]