<a href="https://colab.research.google.com/github/SonyZaman/Python/blob/main/19_Numpy_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[44, 69, 17,  2],
       [86, 72, 99, 84],
       [71, 53, 35, 17],
       [24, 51, 38,  5],
       [11, 87, 52, 26],
       [80,  1, 24, 16]])

In [4]:
# ascending sort
np.sort(a)

array([ 1,  4, 13, 18, 21, 21, 23, 30, 32, 33, 40, 50, 60, 67, 97])

In [5]:
# descending sort
np.sort(a)[::-1]

array([97, 67, 60, 50, 40, 33, 32, 30, 23, 21, 21, 18, 13,  4,  1])

In [6]:
# col-wise sort
np.sort(b,axis=1)
np.sort(b,axis=0)

array([[11,  1, 17,  2],
       [24, 51, 24,  5],
       [44, 53, 35, 16],
       [71, 69, 38, 17],
       [80, 72, 52, 26],
       [86, 87, 99, 84]])

In [7]:
# row-wise sort
np.sort(b,axis=1)

array([[ 2, 17, 44, 69],
       [72, 84, 86, 99],
       [17, 35, 53, 71],
       [ 5, 24, 38, 51],
       [11, 26, 52, 87],
       [ 1, 16, 24, 80]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
# code
np.append(a,200)

array([ 40,  21,  32,  13,   1,  23,  50,  97,  60,   4,  30,  21,  18,
        67,  33, 200])

In [9]:
b

array([[44, 69, 17,  2],
       [86, 72, 99, 84],
       [71, 53, 35, 17],
       [24, 51, 38,  5],
       [11, 87, 52, 26],
       [80,  1, 24, 16]])

In [10]:
# np.append(array, values)
# np.ones((rows, cols))

# append without axis → array becomes flattened (1D)
np.append(b, np.ones((b.shape[0], 1)))

array([44., 69., 17.,  2., 86., 72., 99., 84., 71., 53., 35., 17., 24.,
       51., 38.,  5., 11., 87., 52., 26., 80.,  1., 24., 16.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [11]:
# append a new column of 1's to the array
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[44., 69., 17.,  2.,  1.],
       [86., 72., 99., 84.,  1.],
       [71., 53., 35., 17.,  1.],
       [24., 51., 38.,  5.,  1.],
       [11., 87., 52., 26.,  1.],
       [80.,  1., 24., 16.,  1.]])

In [12]:
# append a new column containing random values between 0 and 1
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[44.        , 69.        , 17.        ,  2.        ,  0.87666626],
       [86.        , 72.        , 99.        , 84.        ,  0.42426705],
       [71.        , 53.        , 35.        , 17.        ,  0.68040947],
       [24.        , 51.        , 38.        ,  5.        ,  0.45544468],
       [11.        , 87.        , 52.        , 26.        ,  0.64498602],
       [80.        ,  1.        , 24.        , 16.        ,  0.97589036]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [13]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c,end='\n\n')
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [16]:
# array
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [17]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [18]:
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [19]:
# code
a.shape

(15,)

In [20]:
np.expand_dims(a,axis=0)

array([[40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33]])

In [21]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [22]:
np.expand_dims(a,axis=1)

array([[40],
       [21],
       [32],
       [13],
       [ 1],
       [23],
       [50],
       [97],
       [60],
       [ 4],
       [30],
       [21],
       [18],
       [67],
       [33]])

In [23]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [24]:
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [25]:
# np.where(condition)

# find all indices with value greater than 50
np.where(a>50)

(array([ 7,  8, 13]),)

In [26]:
# np.where(condition, value_if_true, value_if_false)

# replace all values > 50 with 0
np.where(a>50,0,a)

array([40, 21, 32, 13,  1, 23, 50,  0,  0,  4, 30, 21, 18,  0, 33])

In [27]:
np.where(a%2 == 0,0,a)

array([ 0, 21,  0, 13,  1, 23,  0, 97,  0,  0,  0, 21,  0, 67, 33])

### np.argmax and np.argmin

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

The numpy.argmin() function returns indices of the min element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [34]:
# code
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [35]:
np.argmax(a)

np.int64(7)

In [36]:
b

array([[44, 69, 17,  2],
       [86, 72, 99, 84],
       [71, 53, 35, 17],
       [24, 51, 38,  5],
       [11, 87, 52, 26],
       [80,  1, 24, 16]])

In [37]:
# col-wise max
np.argmax(b,axis=0)

array([1, 4, 1, 1])

In [38]:
# row-wise max
np.argmax(b,axis=1)

array([1, 2, 0, 1, 1, 0])

In [39]:
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [40]:
# np.argmin
np.argmin(a)

np.int64(4)

### np.cumsum and np.cumrod

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

numpy.cumsum() function is used when we want to compute the cumulative product of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [41]:
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [42]:
np.cumsum(a)

array([ 40,  61,  93, 106, 107, 130, 180, 277, 337, 341, 371, 392, 410,
       477, 510])

In [43]:
b

array([[44, 69, 17,  2],
       [86, 72, 99, 84],
       [71, 53, 35, 17],
       [24, 51, 38,  5],
       [11, 87, 52, 26],
       [80,  1, 24, 16]])

In [44]:
np.cumsum(b)

array([  44,  113,  130,  132,  218,  290,  389,  473,  544,  597,  632,
        649,  673,  724,  762,  767,  778,  865,  917,  943, 1023, 1024,
       1048, 1064])

In [45]:
np.cumsum(b,axis=0)

array([[ 44,  69,  17,   2],
       [130, 141, 116,  86],
       [201, 194, 151, 103],
       [225, 245, 189, 108],
       [236, 332, 241, 134],
       [316, 333, 265, 150]])

In [46]:
np.cumsum(b,axis=1)

array([[ 44, 113, 130, 132],
       [ 86, 158, 257, 341],
       [ 71, 124, 159, 176],
       [ 24,  75, 113, 118],
       [ 11,  98, 150, 176],
       [ 80,  81, 105, 121]])

In [47]:
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [48]:
# np.cumprod
np.cumprod(a)

array([                  40,                  840,                26880,
                     349440,               349440,              8037120,
                  401856000,          38980032000,        2338801920000,
              9355207680000,      280656230400000,     5893780838400000,
         106088055091200000,  7107899691110400000, -5246983151580971008])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [49]:
a

array([40, 21, 32, 13,  1, 23, 50, 97, 60,  4, 30, 21, 18, 67, 33])

In [50]:
np.percentile(a,50)

np.float64(30.0)

In [51]:
np.median(a)

np.float64(30.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [72]:
# code
a = np.array([2,7,10,13,15,21,25,29,30,32,36,40,45,50,56,67,70,86,100])
a

array([  2,   7,  10,  13,  15,  21,  25,  29,  30,  32,  36,  40,  45,
        50,  56,  67,  70,  86, 100])

In [75]:
# 0-9 -> 2
# 10-19 -> 3
# 20-29 -> 3
# 30-39 -> 3
# 40-49 -> 2
# 50-59 -> 2
# 60-69 -> 1
# ....
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100,110])

(array([2, 3, 3, 3, 2, 2, 1, 1, 1, 0, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110]))

In [81]:
# 0-59 -> 13
# 60-110 -> 6
np.histogram(a,bins=[0,50,110])

(array([13,  6]), array([  0,  50, 110]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [82]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [83]:
# code
a


array([  2,   7,  10,  13,  15,  21,  25,  29,  30,  32,  36,  40,  45,
        50,  56,  67,  70,  86, 100])

In [84]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([ 10,  30,  40,  50,  70, 100])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [85]:
# code
a

array([  2,   7,  10,  13,  15,  21,  25,  29,  30,  32,  36,  40,  45,
        50,  56,  67,  70,  86, 100])

In [86]:
np.flip(a)

array([100,  86,  70,  67,  56,  50,  45,  40,  36,  32,  30,  29,  25,
        21,  15,  13,  10,   7,   2])

In [87]:
b

array([[44, 69, 17,  2],
       [86, 72, 99, 84],
       [71, 53, 35, 17],
       [24, 51, 38,  5],
       [11, 87, 52, 26],
       [80,  1, 24, 16]])

In [89]:
np.flip(b,axis=0)

array([[80,  1, 24, 16],
       [11, 87, 52, 26],
       [24, 51, 38,  5],
       [71, 53, 35, 17],
       [86, 72, 99, 84],
       [44, 69, 17,  2]])

In [88]:
np.flip(b,axis=1)

array([[ 2, 17, 69, 44],
       [84, 99, 72, 86],
       [17, 35, 53, 71],
       [ 5, 38, 51, 24],
       [26, 52, 87, 11],
       [16, 24,  1, 80]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [90]:
# code
a

array([  2,   7,  10,  13,  15,  21,  25,  29,  30,  32,  36,  40,  45,
        50,  56,  67,  70,  86, 100])

In [91]:
np.put(a,[0,1],[110,530])

In [92]:
a

array([110, 530,  10,  13,  15,  21,  25,  29,  30,  32,  36,  40,  45,
        50,  56,  67,  70,  86, 100])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [93]:
# code
a

array([110, 530,  10,  13,  15,  21,  25,  29,  30,  32,  36,  40,  45,
        50,  56,  67,  70,  86, 100])

In [94]:
np.delete(a,[0,2,4])

array([530,  13,  21,  25,  29,  30,  32,  36,  40,  45,  50,  56,  67,
        70,  86, 100])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.isin

In [100]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [101]:
np.intersect1d(m,n)

array([3, 4, 5])

In [102]:
np.setdiff1d(n,m)

array([6, 7])

In [103]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [105]:
#
m[np.isin(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [106]:
# code
a

array([110, 530,  10,  13,  15,  21,  25,  29,  30,  32,  36,  40,  45,
        50,  56,  67,  70,  86, 100])

In [109]:
np.clip(a,a_min=20,a_max=50)

array([50, 50, 20, 20, 20, 21, 25, 29, 30, 32, 36, 40, 45, 50, 50, 50, 50,
       50, 50])

### Advanced NumPy Functions

In [110]:
# np.swapaxes
# Swap the axes of a 2D array b
print("Original array b:\n", b)
swapped_b = np.swapaxes(b, 0, 1)
print("\nArray b after swapping axes:\n", swapped_b)

Original array b:
 [[44 69 17  2]
 [86 72 99 84]
 [71 53 35 17]
 [24 51 38  5]
 [11 87 52 26]
 [80  1 24 16]]

Array b after swapping axes:
 [[44 86 71 24 11 80]
 [69 72 53 51 87  1]
 [17 99 35 38 52 24]
 [ 2 84 17  5 26 16]]


In [116]:
# np.random.uniform (assuming 'np.uniform' refers to this)
# Generate 5 random numbers between 0 and 1 from a uniform distribution
uniform_numbers = np.random.uniform(low=0.0, high=1.0, size=5)
print("Uniformly distributed random numbers:\n", uniform_numbers)

Uniformly distributed random numbers:
 [0.00313004 0.80903181 0.20991446 0.46286965 0.53940411]


In [117]:
# np.count_nonzero
# Count non-zero elements in array 'a'
print("Original array a:\n", a)
non_zero_count_a = np.count_nonzero(a)
print("Number of non-zero elements in 'a':", non_zero_count_a)

# Create an array with zeros to demonstrate
arr_with_zeros = np.array([0, 1, 0, 5, 0, 3])
non_zero_count_zeros = np.count_nonzero(arr_with_zeros)
print("Array with zeros:\n", arr_with_zeros)
print("Number of non-zero elements in arr_with_zeros:", non_zero_count_zeros)

Original array a:
 [110 530  10  13  15  21  25  29  30  32  36  40  45  50  56  67  70  86
 100]
Number of non-zero elements in 'a': 19
Array with zeros:
 [0 1 0 5 0 3]
Number of non-zero elements in arr_with_zeros: 3


In [118]:
# np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

x = np.array([0, 1, 2])
print("Original array x:\n", x)

# Tile x 3 times along the first dimension
tiled_x = np.tile(x, 3)
print("\nArray tiled 3 times:\n", tiled_x)

# Tile x with specific repetitions
y = np.array([[0, 1], [2, 3]])
print("\nOriginal array y:\n", y)
tiled_y = np.tile(y, (2, 2))
print("\nArray y tiled (2,2) times:\n", tiled_y)

Original array x:
 [0 1 2]

Array tiled 3 times:
 [0 1 2 0 1 2 0 1 2]

Original array y:
 [[0 1]
 [2 3]]

Array y tiled (2,2) times:
 [[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]


In [119]:
# np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

x = np.array([1, 2, 3])
print("Original array x:\n", x)

# Repeat each element 2 times
repeated_x = np.repeat(x, 2)
print("\nElements repeated 2 times:\n", repeated_x)

# Repeat with a 2D array along axis 0
y = np.array([[1, 2], [3, 4]])
print("\nOriginal array y:\n", y)
repeated_y_axis0 = np.repeat(y, 2, axis=0)
print("\nElements repeated along axis 0:\n", repeated_y_axis0)

# Repeat with a 2D array along axis 1
repeated_y_axis1 = np.repeat(y, 2, axis=1)
print("\nElements repeated along axis 1:\n", repeated_y_axis1)

Original array x:
 [1 2 3]

Elements repeated 2 times:
 [1 1 2 2 3 3]

Original array y:
 [[1 2]
 [3 4]]

Elements repeated along axis 0:
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]

Elements repeated along axis 1:
 [[1 1 2 2]
 [3 3 4 4]]


In [120]:
# np.allclose and np.array_equal (for 'equals')

# np.allclose: check if two arrays are element-wise equal within a tolerance
a1 = np.array([1.0, 2.0, 3.0])
a2 = np.array([1.00000001, 2.0, 2.99999999])
a3 = np.array([1.1, 2.0, 3.0])

print(f"Are a1 and a2 allclose? {np.allclose(a1, a2)}")
print(f"Are a1 and a3 allclose? {np.allclose(a1, a3)}")
print(f"Are a1 and a3 allclose with custom tolerance? {np.allclose(a1, a3, atol=0.1)}")

# np.array_equal: check if two arrays have the same shape and elements
b1 = np.array([1, 2, 3])
b2 = np.array([1, 2, 3])
b3 = np.array([1, 2, 4])
b4 = np.array([[1, 2, 3]])

print(f"\nAre b1 and b2 array_equal? {np.array_equal(b1, b2)}")
print(f"Are b1 and b3 array_equal? {np.array_equal(b1, b3)}")
print(f"Are b1 and b4 array_equal (different shape)? {np.array_equal(b1, b4)}")

# Direct equality check (element-wise comparison)
print(f"\nElement-wise equality (b1 == b2): {b1 == b2}")
print(f"Element-wise equality (b1 == b3): {b1 == b3}")

Are a1 and a2 allclose? True
Are a1 and a3 allclose? False
Are a1 and a3 allclose with custom tolerance? True

Are b1 and b2 array_equal? True
Are b1 and b3 array_equal? False
Are b1 and b4 array_equal (different shape)? False

Element-wise equality (b1 == b2): [ True  True  True]
Element-wise equality (b1 == b3): [ True  True False]
